# Generated by Django 3.2.4 on 2021-07-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='inventory_score',
            field=models.IntegerField(default=0),
        ),
    ]
